# Generated by Django 5.2.4 on 2025-08-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camtelfeedback',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camtelfeedback',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camtelfeedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camtelfeedback',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mtnfeedback',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mtnfeedback',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mtnfeedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mtnfeedback',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nexttelfeedback',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nexttelfeedback',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nexttelfeedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nexttelfeedback',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orangefeedback',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orangefeedback',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orangefeedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orangefeedback',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
